version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /load-generator
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /plugins
    schedule:
      interval: weekly
    # Disable all pull requests for plugins folder
    open-pull-requests-limit: 0
