apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  namespace: openshift-gitops
  name: rhdh-loadtest
spec:
  description: rhdh-loadtest applications
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
