apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: openshift-gitops
  name: rhdh-loadtests-app-of-legacy-apps
spec:
  project: rhdh-loadtests
  source:
    repoURL: 'https://github.com/redhat-developer/rhdh-loadtest.git'
    targetRevision: HEAD
    path: argocd/legacy-apps
  destination:
    name: in-cluster
    namespace: openshift-gitops
  syncPolicy:
    automated:
      enabled: true
