FROM mcr.microsoft.com/playwright:v1.61.1-resolute
WORKDIR /app
RUN corepack enable
COPY package.json yarn.lock .yarnrc.yml ./
COPY .yarn .yarn
RUN yarn install --immutable
COPY . .
CMD ["yarn", "test"]
