apiVersion: batch/v1
kind: Job
metadata:
  generateName: rhdh-loadtest-
spec:
  ttlSecondsAfterFinished: 86400
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: loadtest
          image: quay.io/rhdh-community/rhdh-loadtest-generator
          env:
            - name: FORCE_COLOR
              value: "true"
            - name: PLAYWRIGHT_JSON_OUTPUT_FILE
              value: /tmp/playwright/test-results.json
          command: ["sh", "-c", "yarn playwright test --output /tmp/playwright/test-results && yarn analyse"]
